@echo off

START "" "%~dp0son ta mere\script ta maman\volume_max.bat"
START "" "%~dp0son ta mere\soupire\You are an idiot!!.mp4"
START "" "%~dp0son ta mere\script ta maman\voix .vbs"
START "" "%~dp0son ta mere\script ta maman\ha.bat"
START "" "%~dp0son ta mere\script ta maman\fond d'ecrant2.bat"
START "" "%~dp0son ta mere\images\lol 1.jfif"
START "" "%~dp0son ta mere\images\lol 3.jfif"
START "" "%~dp0son ta mere\images\lol 4.jfif"
START "" "%~dp0son ta mere\images\lol 5.jfif"
START "" "%~dp0son ta mere\images\lol 6.jfif"
START "" "%~dp0son ta mere\images\lol 7.jfif"
START "" "%~dp0son ta mere\images\lol 8.jfif"
START "" "%~dp0son ta mere\images\lol 9.jfif"
START "" "%~dp0son ta mere\images\lol 10.jfif"
START "" "%~dp0son ta mere\images\lol 11.jfif"
START "" "%~dp0son ta mere\images\lol 12.jfif"
START "" "%~dp0son ta mere\images\lol 13.jfif"
START "" "%~dp0son ta mere\images\lol 14.jfif"
START "" "%~dp0son ta mere\images\lol 1.jfif"
START "" "%~dp0son ta mere\images\lol 3.jfif"
START "" "%~dp0son ta mere\images\lol 4.jfif"
START "" "%~dp0son ta mere\images\lol 5.jfif"
START "" "%~dp0son ta mere\images\lol 6.jfif"
START "" "%~dp0son ta mere\images\lol 7.jfif"
START "" "%~dp0son ta mere\images\lol 8.jfif"
START "" "%~dp0son ta mere\images\lol 9.jfif"
START "" "%~dp0son ta mere\images\lol 10.jfif"
START "" "%~dp0son ta mere\images\lol 11.jfif"
START "" "%~dp0son ta mere\images\lol 12.jfif"
START "" "%~dp0son ta mere\images\lol 13.jfif"
START "" "%~dp0son ta mere\images\lol 14.jfif"
START "" "%~dp0son ta mere\images\lol 1.jfif"
START "" "%~dp0son ta mere\images\lol 3.jfif"
START "" "%~dp0son ta mere\images\lol 4.jfif"
START "" "%~dp0son ta mere\images\lol 5.jfif"
START "" "%~dp0son ta mere\images\lol 6.jfif"
START "" "%~dp0son ta mere\images\lol 7.jfif"
START "" "%~dp0son ta mere\images\lol 8.jfif"
START "" "%~dp0son ta mere\images\lol 9.jfif"
START "" "%~dp0son ta mere\images\lol 10.jfif"
START "" "%~dp0son ta mere\images\lol 11.jfif"
START "" "%~dp0son ta mere\images\lol 12.jfif"
START "" "%~dp0son ta mere\images\lol 13.jfif"
START "" "%~dp0son ta mere\images\lol 14.jfif"
START "" "%~dp0son ta mere\script ta maman\lol.bat"
START "" "%~dp0son ta mere\script ta maman\stop.bat"
START "" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
